import type {
  HistoricalJobLink,
  JobApplicationChannel,
  NeedsManualReviewJob,
  SuggestedNewChannel,
} from "@/lib/types";

const nowIso = () => new Date().toISOString();

export const jobApplicationChannels: JobApplicationChannel[] = [
  {
    id: "channel_web3_career",
    name: "Web3.career",
    channelType: "job_board",
    url: "https://web3.career/",
    topic: "web3",
    enabled: true,
    qualityTier: "Tier 2",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Live ingestion via public HR-filtered listing pages.",
  },
  {
    id: "channel_cryptocurrencyjobs",
    name: "Cryptocurrency Jobs",
    channelType: "job_board",
    url: "https://cryptocurrencyjobs.co/",
    topic: "web3",
    enabled: true,
    qualityTier: "Tier 2",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Live ingestion via public RSS (index.xml).",
  },
  {
    id: "channel_linkedin_saved_search_pp_web3_ai",
    name: "LinkedIn Job Alerts (Hotmail / Outlook)",
    channelType: "linkedin_saved_search",
    url: "https://www.linkedin.com/jobs/",
    topic: "jobs",
    enabled: true,
    qualityTier: "Tier 1",
    usedBy: ["job_opportunities", "settings"],
    lastCheckedAt: nowIso(),
    notes:
      "LinkedIn saved-search job alerts ingested from Outlook/Hotmail via Microsoft Power Automate → SWIFT /api/job-alert-ingest. No LinkedIn page scraping.",
  },
  {
    id: "channel_coinbase_careers",
    name: "Target Company Careers - Coinbase",
    channelType: "company_careers",
    url: "https://www.coinbase.com/careers",
    topic: "web3",
    enabled: true,
    qualityTier: "Tier 1",
    usedBy: ["job_opportunities", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Target company career page. Mock memory until ingestion is connected.",
  },
  {
    id: "channel_anthropic_careers",
    name: "Target Company Careers - Anthropic",
    channelType: "company_careers",
    url: "https://www.anthropic.com/careers",
    topic: "ai",
    enabled: true,
    qualityTier: "Tier 1",
    usedBy: ["job_opportunities", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Target company career page. Mock memory until ingestion is connected.",
  },
  {
    id: "channel_openai_careers",
    name: "Target Company Careers - OpenAI",
    channelType: "company_careers",
    url: "https://openai.com/careers",
    topic: "ai",
    enabled: true,
    qualityTier: "Tier 1",
    usedBy: ["job_opportunities", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Target company career page. Mock memory until ingestion is connected.",
  },
  {
    id: "channel_binance_careers",
    name: "Target Company Careers - Binance",
    channelType: "company_careers",
    url: "https://www.binance.com/en/careers",
    topic: "web3",
    enabled: false,
    qualityTier: "Tier 2",
    usedBy: ["job_opportunities", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Optional channel. Disabled in mock memory until prioritised.",
  },
  {
    id: "channel_kraken_careers",
    name: "Target Company Careers - Kraken",
    channelType: "company_careers",
    url: "https://www.kraken.com/careers",
    topic: "web3",
    enabled: true,
    qualityTier: "Tier 1",
    usedBy: ["job_opportunities", "settings"],
    lastCheckedAt: nowIso(),
    notes: "Target company career page. Mock memory until ingestion is connected.",
  },
];

export const historicalJobLinks: HistoricalJobLink[] = [
  {
    id: "hist_job_senior_people_partner",
    role: "Senior People Partner (AI / Product)",
    company: "Example AI Co",
    location: "London (Hybrid)",
    source: "LinkedIn",
    applyUrl: "https://example.com/apply/senior-people-partner",
    dateFound: nowIso(),
    fitScore: 84,
    applicationStatus: "Interested",
    whyThisFits:
      "Operator HRBP seat with strong cross-functional leadership expectations and AI-adjacent org design.",
    gaps: ["EU works council experience", "Scaled people analytics instrumentation"],
    recommendedAction:
      "Write a 1-page operating model memo: team rituals, decision rights, and metrics for AI product teams.",
    notes: "Mock example until real job ingestion is connected.",
  },
  {
    id: "hist_job_people_partner_gtm",
    role: "People Partner, GTM",
    company: "Example Web3 Co",
    location: "Remote (EU)",
    source: "Company careers",
    applyUrl: "https://example.com/apply/people-partner-gtm",
    dateFound: nowIso(),
    fitScore: 78,
    applicationStatus: "To Review",
    whyThisFits:
      "Commercial org focus with performance cadence and comp hygiene; aligned to HRBP operator layer.",
    gaps: ["Deep compensation banding work", "RevOps operating rhythm exposure"],
    recommendedAction:
      "Draft a quarterly performance cadence and propose a clean comp narrative for critical roles.",
    notes: "Mock example until real job ingestion is connected.",
  },
  {
    id: "hist_job_hrbp_risk_compliance",
    role: "HRBP, Compliance & Risk",
    company: "Example Exchange",
    location: "Dublin (Onsite)",
    source: "Recruiter",
    applyUrl: "https://example.com/apply/hrbp-risk-compliance",
    dateFound: nowIso(),
    fitScore: 72,
    applicationStatus: "Archived",
    whyThisFits:
      "Regulatory environment supports compliance-ready growth capability building, but onsite preference is a constraint.",
    gaps: ["Onsite requirement", "ER playbooks for regulated environments"],
    recommendedAction:
      "Build a capability map for compliance-ready growth and position HRBP value via risk controls and workforce planning.",
    notes: "Mock example until real job ingestion is connected.",
  },
];

export const suggestedNewChannels: SuggestedNewChannel[] = [
  {
    id: "suggest_wellfound",
    channelName: "Wellfound",
    channelType: "job_board",
    url: "https://wellfound.com/",
    reasonToAdd:
      "High density of startup roles; useful for early-stage AI operator and people partner positions.",
    expectedSignal: "New People/HRBP roles at AI startups with strong execution expectations.",
    priority: "High",
    status: "Suggested",
  },
  {
    id: "suggest_remote3",
    channelName: "Remote3",
    channelType: "job_board",
    url: "https://remote3.co/",
    reasonToAdd:
      "Web3 remote opportunities across functions; can widen coverage beyond a single job board.",
    expectedSignal: "Remote-friendly Web3 roles and emerging hiring clusters by category.",
    priority: "Medium",
    status: "Suggested",
  },
  {
    id: "suggest_built_in",
    channelName: "Built In",
    channelType: "job_board",
    url: "https://builtin.com/jobs",
    reasonToAdd:
      "Broader tech coverage; good benchmark for AI-adjacent people roles and comp/leveling expectations.",
    expectedSignal: "Patterns in people partner roles tied to AI/product orgs.",
    priority: "Medium",
    status: "Suggested",
  },
  {
    id: "suggest_greenhouse_boards",
    channelName: "Greenhouse company boards",
    channelType: "manual",
    url: "https://www.greenhouse.io/",
    reasonToAdd:
      "Many target companies use Greenhouse; enables scalable capture of careers pages once ingestion exists.",
    expectedSignal: "Direct application links and structured role metadata across target companies.",
    priority: "High",
    status: "Approved",
  },
  {
    id: "suggest_lever_boards",
    channelName: "Lever company boards",
    channelType: "manual",
    url: "https://www.lever.co/",
    reasonToAdd:
      "Many high-growth AI/Web3 companies use Lever; useful for consistent role metadata ingestion.",
    expectedSignal: "Role metadata + apply links for target companies using Lever.",
    priority: "High",
    status: "Suggested",
  },
  {
    id: "suggest_pmp_jobs",
    channelName: "People Managing People Jobs",
    channelType: "community",
    url: "https://peoplemanagingpeople.com/",
    reasonToAdd:
      "HR practitioner community that may surface niche roles and hiring signals relevant to HRBPs.",
    expectedSignal: "HRBP/People Partner role postings and community-sourced opportunities.",
    priority: "Low",
    status: "Suggested",
  },
];

export const needsManualReviewJobs: NeedsManualReviewJob[] = [
  {
    id: "review_job_unknown_apply",
    roleHint: "People Partner (AI) — link missing",
    companyHint: "Example AI Co",
    sourceName: "Newsletter digest",
    sourceUrl: "https://example.com/source/newsletter-digest",
    reason: "Role mentioned without a stable application URL; needs manual verification.",
  },
  {
    id: "review_job_unclear_company",
    roleHint: "HRBP, Web3 Compliance — company unclear",
    sourceName: "Community post",
    sourceUrl: "https://example.com/source/community-post",
    reason: "Company name not explicit; needs manual review before saving a historical link.",
  },
];

