import type {
  JobOpportunity,
  LearningAsset,
  LearningAssetHistory,
  SkillToPickUp,
} from "@/lib/types";

export type { LearningAsset } from "@/lib/types";

const nowIso = () => new Date().toISOString();

export const mockOpportunities: JobOpportunity[] = [
  {
    id: "opp_axiom_labs_hrbp_ai",
    role: "HRBP, Product & Engineering (AI)",
    company: "Axiom Labs",
    location: "London (Hybrid)",
    source: "LinkedIn",
    url: "https://example.com/jobs/axiom-labs-hrbp-ai",
    applyUrl: "https://example.com/apply/axiom-labs-hrbp-ai",
    dateFound: nowIso(),
    fitScore: 86,
    seniorityFit: "High",
    sectorFit: "High",
    whyThisFits:
      "High-leverage HRBP seat where operating model + capability mapping are core deliverables.",
    gaps: ["Deep hands-on people analytics instrumentation", "EU works council exposure"],
    recommendedAction:
      "Prepare a 30/60/90 with AI operating model changes + manager enablement plan.",
  },
  {
    id: "opp_ledgerline_people_partner_gtm",
    role: "People Partner, GTM & RevOps",
    company: "Ledgerline",
    location: "Remote (EU)",
    source: "Company site",
    url: "https://example.com/jobs/ledgerline-people-partner-gtm",
    applyUrl: "https://example.com/apply/ledgerline-people-partner-gtm",
    dateFound: nowIso(),
    fitScore: 81,
    seniorityFit: "Medium",
    sectorFit: "Medium",
    whyThisFits:
      "Strong match for commercial org design, performance cadence, and comp/IC hygiene.",
    gaps: ["Crypto market cycles narrative", "Comp banding at scale"],
    recommendedAction:
      "Draft a comp + performance cadence proposal for lean GTM teams.",
  },
  {
    id: "opp_northbridge_web3_hrbp_risk",
    role: "Senior HRBP, Compliance & Risk",
    company: "Northbridge Web3",
    location: "Dublin (Onsite)",
    source: "Recruiter",
    url: "https://example.com/jobs/northbridge-web3-hrbp-risk",
    applyUrl: "https://example.com/apply/northbridge-web3-hrbp-risk",
    dateFound: nowIso(),
    fitScore: 77,
    seniorityFit: "High",
    sectorFit: "High",
    whyThisFits:
      "Regulatory-facing operating rhythm; ideal for compliance-ready growth and ER risk posture.",
    gaps: ["Onsite preference", "Specialist ER playbooks"],
    recommendedAction:
      "Map compliance capability roles and propose hiring vs upskilling splits.",
  },
];

export const mockSkills: SkillToPickUp[] = [
  {
    id: "skill_ai_operating_model_design",
    skill: "AI Operating Model Design",
    category: "AI / Automation",
    priority: "High",
    evidence:
      "More roles require HRBP input on work decomposition: automate vs augment vs human-led.",
    currentLevel: "Working",
    targetLevel: "Expert",
    nextAction:
      "Create a repeatable operating model canvas: work types, ownership, decision rights, metrics.",
    relatedAsset: "People Strategy & Operating Model",
  },
  {
    id: "skill_hr_analytics_exec_decisions",
    skill: "HR Analytics for Executive Decisions",
    category: "Data / Analytics",
    priority: "High",
    evidence:
      "Signals show lean teams want precision: capacity, productivity, attrition risk, and role criticality.",
    currentLevel: "Beginner",
    targetLevel: "Strong",
    nextAction:
      "Define 8–10 HRBP-ready metrics and how they translate to leadership actions each week.",
    relatedAsset: "HR Metrics & People Analytics",
  },
  {
    id: "skill_comp_narrative_web3_ai",
    skill: "Compensation Narrative for Web3/AI",
    category: "Web3 / Crypto",
    priority: "Medium",
    evidence:
      "Market volatility pushes more scrutiny on cash/eq mix, leveling, and role-based value.",
    currentLevel: "Working",
    targetLevel: "Strong",
    nextAction:
      "Draft a comp philosophy one-pager with scenarios for hiring freezes and critical roles.",
    relatedAsset: "Compensation & Reward",
  },
];

export const mockLearningAssets: LearningAsset[] = [
  {
    id: "asset_people_strategy_operating_model",
    topic: "People Strategy & Operating Model",
    purpose: "Turn market signals into practical org design and decision rhythms.",
    priority: "High",
    status: "Drafting",
    marketDemandScore: 88,
    trend: "Increasing",
    plannedAsset: "Executive playbook: AI-native HRBP operating model",
    nextAction: "Draft 3 operating model archetypes for lean AI teams.",
    lastChangedAt: nowIso(),
    changeReason: "Upgraded to Drafting after initial outline review.",
  },
  {
    id: "asset_talent_acquisition",
    topic: "Talent Acquisition",
    purpose: "Translate capability bets into sharper role definitions and hiring plans.",
    priority: "Medium",
    status: "Researching",
    marketDemandScore: 74,
    trend: "Stable",
    plannedAsset: "Role scorecards + capability interview kit",
    nextAction: "Collect 10 role profiles across AI/Web3 operators and map common patterns.",
    lastChangedAt: nowIso(),
    changeReason: "Added sources and started research notes.",
  },
  {
    id: "asset_talent_management",
    topic: "Talent Management",
    purpose: "Build retention and progression signals for small, senior-heavy teams.",
    priority: "Medium",
    status: "Planned",
    marketDemandScore: 71,
    trend: "Stable",
    plannedAsset: "Lean-team talent review blueprint",
    nextAction: "Define a 45-minute quarterly talent review agenda with action outputs.",
    lastChangedAt: nowIso(),
    changeReason: "Queued for next month’s drafting sprint.",
  },
  {
    id: "asset_performance_management",
    topic: "Performance Management",
    purpose: "Create execution cadence and decision clarity under uncertainty.",
    priority: "High",
    status: "Researching",
    marketDemandScore: 83,
    trend: "Increasing",
    plannedAsset: "Performance cadence template for operator-led teams",
    nextAction: "Draft a 4-week cycle: goals → signals → decisions → coaching actions.",
    lastChangedAt: nowIso(),
    changeReason: "Prioritised based on rising leadership demand for cadence clarity.",
  },
  {
    id: "asset_compensation_reward",
    topic: "Compensation & Reward",
    purpose: "Support compensation decisions aligned to critical capabilities.",
    priority: "High",
    status: "Researching",
    marketDemandScore: 86,
    trend: "Increasing",
    plannedAsset: "Comp philosophy + leveling narrative for Web3/AI",
    nextAction: "Create 3 scenarios for cash/eq trade-offs by role criticality.",
    lastChangedAt: nowIso(),
    changeReason: "Priority increased due to market volatility and hiring scrutiny.",
  },
  {
    id: "asset_hr_metrics_people_analytics",
    topic: "HR Metrics & People Analytics",
    purpose: "Provide weekly executive-ready people insights and actions.",
    priority: "High",
    status: "Drafting",
    marketDemandScore: 90,
    trend: "Increasing",
    plannedAsset: "Weekly HRBP metrics pack: signals-to-actions",
    nextAction: "Define the leading indicators for productivity and attrition risk.",
    lastChangedAt: nowIso(),
    changeReason: "Drafting started to support weekly exec decision-making.",
  },
  {
    id: "asset_org_design_workforce_planning",
    topic: "Organisation Design & Workforce Planning",
    purpose: "Ensure workforce shape matches strategy while staying lean.",
    priority: "Medium",
    status: "Planned",
    marketDemandScore: 78,
    trend: "Stable",
    plannedAsset: "Workforce planning sprint kit",
    nextAction: "Draft a 2-week planning sprint with inputs/outputs and stakeholder roles.",
    lastChangedAt: nowIso(),
    changeReason: "Held in backlog until core metrics pack is established.",
  },
  {
    id: "asset_change_management",
    topic: "Change Management",
    purpose: "Help leaders execute operating model shifts without cultural debt.",
    priority: "Medium",
    status: "Drafting",
    marketDemandScore: 76,
    trend: "Emerging",
    plannedAsset: "Change narrative + manager enablement package",
    nextAction: "Write a change storyline template for AI adoption waves.",
    lastChangedAt: nowIso(),
    changeReason: "Moved from Planned to Drafting for AI adoption communications.",
  },
  {
    id: "asset_leadership_manager_effectiveness",
    topic: "Leadership & Manager Effectiveness",
    purpose: "Increase decision quality and coaching clarity in high-velocity teams.",
    priority: "High",
    status: "Planned",
    marketDemandScore: 85,
    trend: "Increasing",
    plannedAsset: "Manager operating system: rituals, feedback, and prioritization",
    nextAction: "Draft a 6-ritual manager system for lean teams.",
    lastChangedAt: nowIso(),
    changeReason: "Scheduled once performance cadence framework is drafted.",
  },
  {
    id: "asset_employee_experience_culture",
    topic: "Employee Experience & Culture",
    purpose: "Sustain engagement while teams scale selectively.",
    priority: "Low",
    status: "Planned",
    marketDemandScore: 62,
    trend: "Stable",
    plannedAsset: "Experience principles for hybrid operator teams",
    nextAction: "Define 5 culture principles tied to execution and risk posture.",
    lastChangedAt: nowIso(),
    changeReason: "Lower urgency versus operating model and performance cadence work.",
  },
  {
    id: "asset_employee_relations_risk",
    topic: "Employee Relations & Risk",
    purpose: "Reduce risk exposure as compliance scrutiny increases.",
    priority: "Medium",
    status: "Researching",
    marketDemandScore: 69,
    trend: "Emerging",
    plannedAsset: "ER risk checklist for fast-moving orgs",
    nextAction: "Draft a lightweight ER risk triage framework for HRBPs.",
    lastChangedAt: nowIso(),
    changeReason: "Researching due to increased compliance scrutiny signals.",
  },
  {
    id: "asset_learning_capability_skills",
    topic: "Learning, Capability & Skills",
    purpose: "Turn capability gaps into targeted learning plans.",
    priority: "Medium",
    status: "Planned",
    marketDemandScore: 70,
    trend: "Stable",
    plannedAsset: "Capability roadmap: HRBP skill layer",
    nextAction: "Map skills to outputs and evidence of mastery.",
    lastChangedAt: nowIso(),
    changeReason: "Planned as a supporting asset for the skills layer.",
  },
  {
    id: "asset_dei_inclusion_belonging",
    topic: "DEI, Inclusion & Belonging",
    purpose: "Maintain inclusive decision-making while hiring becomes more selective.",
    priority: "Low",
    status: "Planned",
    marketDemandScore: 60,
    trend: "Stable",
    plannedAsset: "Inclusive hiring + progression safeguards",
    nextAction: "Draft 5 safeguards that fit lean teams without heavy process.",
    lastChangedAt: nowIso(),
    changeReason: "Planned; will be drafted once core hiring scorecards exist.",
  },
  {
    id: "asset_hr_tech_ai_automation",
    topic: "HR Tech, AI & Automation",
    purpose: "Leverage automation to increase HRBP speed and clarity.",
    priority: "High",
    status: "Generated",
    marketDemandScore: 92,
    trend: "Increasing",
    plannedAsset: "AI workflow stack: HRBP intelligence loop",
    nextAction: "Package as a 10-slide exec deck with operating metrics.",
    lastChangedAt: nowIso(),
    changeReason: "Moved from Drafting to Generated after synthesis run.",
  },
  {
    id: "asset_web3_ai_domain_knowledge_hrbp",
    topic: "Web3 / AI Domain Knowledge for HRBP",
    purpose: "Build domain fluency to interpret market signals and hiring shifts.",
    priority: "High",
    status: "Generated",
    marketDemandScore: 89,
    trend: "Emerging",
    plannedAsset: "Domain primer: Web3 x AI for HRBP decisions",
    nextAction: "Generate a glossary + 30-question calibration quiz for leaders.",
    lastChangedAt: nowIso(),
    changeReason: "Moved from Researching to Generated to support exec conversations.",
  },
];

export const mockLearningAssetHistory: LearningAssetHistory[] = [
  {
    id: "hist_hr_tech_ai_automation_status",
    assetId: "asset_hr_tech_ai_automation",
    topic: "HR Tech, AI & Automation",
    date: nowIso(),
    previousStatus: "Drafting",
    newStatus: "Generated",
    marketDemandScore: 92,
    evidenceCount: 14,
    reason: "Initial synthesis completed; ready for packaging.",
    sourceSummary: "Signals across HR tech vendors and operator teams show accelerating adoption.",
  },
  {
    id: "hist_comp_reward_priority",
    assetId: "asset_compensation_reward",
    topic: "Compensation & Reward",
    date: nowIso(),
    previousPriority: "Medium",
    newPriority: "High",
    marketDemandScore: 86,
    evidenceCount: 9,
    reason: "Hiring scrutiny increased; comp narratives now central to decision-making.",
    sourceSummary: "More job specs and leadership posts emphasize leveling, equity mix, and cost control.",
  },
  {
    id: "hist_web3_ai_domain_status",
    assetId: "asset_web3_ai_domain_knowledge_hrbp",
    topic: "Web3 / AI Domain Knowledge for HRBP",
    date: nowIso(),
    previousStatus: "Researching",
    newStatus: "Generated",
    marketDemandScore: 89,
    evidenceCount: 11,
    reason: "Generated to support HRBP credibility in exec conversations.",
    sourceSummary: "Recurring need for HRBP domain fluency surfaced in role expectations and interviews.",
  },
  {
    id: "hist_change_mgmt_status",
    assetId: "asset_change_management",
    topic: "Change Management",
    date: nowIso(),
    previousStatus: "Planned",
    newStatus: "Drafting",
    marketDemandScore: 76,
    evidenceCount: 7,
    reason: "AI adoption waves require stronger change narrative patterns.",
    sourceSummary: "Teams report friction in adoption; managers need practical enablement assets.",
  },
];

export const mockMonthlyChangeLog: string[] = [
  "HR Tech, AI & Automation moved from Drafting to Generated",
  "Compensation & Reward increased from Medium to High",
  "Web3 / AI Domain Knowledge moved from Researching to Generated",
  "Change Management moved from Planned to Drafting",
];

export const mockSettings = {
  sources: ["Company blogs", "LinkedIn", "VC memos", "Substack", "Regulatory updates"],
  searchKeywords: [
    "AI operating model",
    "HRBP productivity",
    "Web3 compliance hiring",
    "People analytics executive pack",
    "RevOps org design",
  ],
  emailRecipient: "raychen@company.com",
  refreshSchedule: "Daily at 06:30 (Europe/London)",
  aiProvider: "DeepSeek (server-side)",
  skillLayer: "HRBP Operator Layer v0.2",
};

