import type {
  SourceRegistryItem,
  SourceTopic,
  SourceType,
  SwiftSection,
} from "@/lib/types";

export const sourceRegistry: SourceRegistryItem[] = [
  {
    id: "coindesk",
    name: "CoinDesk",
    sourceType: "rss",
    topic: "web3",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up"],
    qualityTier: "Tier 2",
    url: "https://www.coindesk.com/arc/outboundfeeds/rss/",
    enabled: true,
    accessType: "public",
    notes: "Crypto and digital assets market news.",
  },
  {
    id: "the_block",
    name: "The Block",
    sourceType: "rss",
    topic: "web3",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up"],
    qualityTier: "Tier 2",
    url: "https://www.theblock.co/rss.xml",
    enabled: true,
    accessType: "public",
    notes: "Institutional crypto, funding, exchange and regulation coverage.",
  },
  {
    id: "a16z_crypto",
    name: "a16z crypto",
    sourceType: "rss",
    topic: "web3",
    category: "web3_ai",
    usedBy: ["dashboard", "learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://a16zcrypto.com/feed/",
    enabled: false,
    accessType: "public",
    notes: "Disabled temporarily because the current RSS URL returned HTTP 404. Needs verified feed URL.",
  },
  {
    id: "coinmarketcap_api",
    name: "CoinMarketCap",
    sourceType: "api",
    topic: "web3",
    category: "web3_ai",
    usedBy: ["dashboard"],
    qualityTier: "Tier 1",
    url: "https://coinmarketcap.com/api/",
    enabled: false,
    accessType: "api_key_required",
    notes: "Better used later as market data API rather than RSS.",
  },
  {
    id: "coingecko_api",
    name: "CoinGecko",
    sourceType: "api",
    topic: "web3",
    category: "web3_ai",
    usedBy: ["dashboard"],
    qualityTier: "Tier 1",
    url: "https://www.coingecko.com/en/api",
    enabled: false,
    accessType: "api_key_required",
    notes: "Market data API for crypto categories, token movement and pricing.",
  },
  {
    id: "glassnode_insights",
    name: "Glassnode Insights",
    sourceType: "newsletter",
    topic: "web3",
    category: "web3_ai",
    usedBy: ["dashboard", "learning_assets"],
    qualityTier: "Tier 1",
    url: "https://insights.glassnode.com/",
    enabled: false,
    accessType: "manual_review",
    notes: "On-chain macro and market structure insights.",
  },

  {
    id: "openai_news",
    name: "OpenAI News",
    sourceType: "rss",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up", "learning_assets"],
    qualityTier: "Tier 1",
    url: "https://openai.com/news/rss.xml",
    enabled: true,
    accessType: "public",
    notes: "Official OpenAI updates.",
  },
  {
    id: "huggingface_blog",
    name: "Hugging Face Blog",
    sourceType: "rss",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up", "learning_assets"],
    qualityTier: "Tier 1",
    url: "https://huggingface.co/blog/feed.xml",
    enabled: true,
    accessType: "public",
    notes: "Open-source AI ecosystem and model/application updates.",
  },
  {
    id: "google_ai_blog",
    name: "Google AI Blog",
    sourceType: "website",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "learning_assets"],
    qualityTier: "Tier 1",
    url: "https://blog.google/technology/ai/",
    enabled: false,
    accessType: "manual_review",
    notes: "Official Google AI updates; ingestion method to be added later.",
  },
  {
    id: "anthropic_news",
    name: "Anthropic / Claude Blog",
    sourceType: "website",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://www.anthropic.com/news",
    enabled: false,
    accessType: "manual_review",
    notes: "Official Anthropic and Claude updates; ingestion method to be added later.",
  },
  {
    id: "follow_builders_x",
    name: "Follow Builders - X Builders",
    sourceType: "json_feed",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up", "learning_assets"],
    qualityTier: "Tier 2",
    url: "https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-x.json",
    enabled: false,
    accessType: "public",
    notes: "Curated AI builder posts from X. JSON feed, not RSS.",
  },
  {
    id: "follow_builders_podcasts",
    name: "Follow Builders - AI Podcasts",
    sourceType: "json_feed",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up", "learning_assets"],
    qualityTier: "Tier 2",
    url: "https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-podcasts.json",
    enabled: false,
    accessType: "public",
    notes: "Curated AI podcast and YouTube transcript intelligence. JSON feed, not RSS.",
  },
  {
    id: "follow_builders_blogs",
    name: "Follow Builders - AI Blogs",
    sourceType: "json_feed",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "learning_assets"],
    qualityTier: "Tier 2",
    url: "https://raw.githubusercontent.com/zarazhangrui/follow-builders/main/feed-blogs.json",
    enabled: false,
    accessType: "public",
    notes: "Curated official AI company blog feed. JSON feed, not RSS.",
  },
  {
    id: "ai_weekly",
    name: "AI Weekly",
    sourceType: "newsletter",
    topic: "ai",
    category: "web3_ai",
    usedBy: ["dashboard", "skills_to_pick_up"],
    qualityTier: "Tier 2",
    url: "https://aiweekly.co/",
    enabled: false,
    accessType: "manual_review",
    notes: "Curated AI updates on funding, models, regulation and applications.",
  },

  {
    id: "gartner_hr",
    name: "Gartner HR",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://www.gartner.com/en/human-resources",
    enabled: false,
    accessType: "manual_review",
    notes: "CHRO priorities, HR trends and leadership research.",
  },
  {
    id: "cipd",
    name: "CIPD",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://www.cipd.org/",
    enabled: false,
    accessType: "manual_review",
    notes: "UK HR professional body, employment practice and people profession research.",
  },
  {
    id: "deloitte_human_capital",
    name: "Deloitte Human Capital",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://www.deloitte.com/global/en/services/consulting/collections/human-capital-trends.html",
    enabled: false,
    accessType: "manual_review",
    notes: "Human capital trends and workforce transformation research.",
  },
  {
    id: "mckinsey_organization",
    name: "McKinsey Organization",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://www.mckinsey.com/capabilities/people-and-organizational-performance",
    enabled: false,
    accessType: "manual_review",
    notes: "People, organisation, talent and transformation insights.",
  },
  {
    id: "josh_bersin",
    name: "Josh Bersin",
    sourceType: "newsletter",
    topic: "hr",
    category: "hrbp",
    usedBy: ["learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 1",
    url: "https://joshbersin.com/",
    enabled: false,
    accessType: "manual_review",
    notes: "HR technology, talent, capability and AI in HR thought leadership.",
  },
  {
    id: "aihr_blog",
    name: "AIHR Blog",
    sourceType: "rss",
    topic: "hr",
    category: "hrbp",
    usedBy: ["dashboard", "learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 2",
    url: "https://www.aihr.com/blog/feed/",
    enabled: true,
    accessType: "public",
    notes: "HR capability, people analytics and practical HR learning.",
  },
  {
    id: "people_managing_people",
    name: "People Managing People",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 2",
    url: "https://peoplemanagingpeople.com/",
    enabled: false,
    accessType: "manual_review",
    notes: "HR and people leadership articles, newsletters and practitioner resources.",
  },
  {
    id: "hacking_hr",
    name: "Hacking HR",
    sourceType: "rss",
    topic: "hr",
    category: "hrbp",
    usedBy: ["dashboard", "learning_assets", "skills_to_pick_up"],
    qualityTier: "Tier 2",
    url: "https://www.hackinghr.io/blog/rss.xml",
    enabled: false,
    accessType: "public",
    notes: "Disabled temporarily because the current RSS URL returned HTTP 404. Needs verified feed URL.",
  },

  {
    id: "web3_career",
    name: "Web3.career",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://web3.career/",
    enabled: true,
    accessType: "public",
    notes: "Web3 job board; SWIFT ingests public HR-filtered listing pages.",
  },
  {
    id: "web3_career_hr_jobs",
    name: "Web3.career HR jobs",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://web3.career/hr-jobs",
    enabled: true,
    accessType: "public",
    notes: "HR-specific Web3 job search page.",
  },
  {
    id: "web3_career_uk_hr_jobs",
    name: "Web3.career UK HR jobs",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://web3.career/web3-jobs-united-kingdom%2Bhr",
    enabled: true,
    accessType: "public",
    notes: "UK HR Web3 roles.",
  },
  {
    id: "web3_career_london_hr_jobs",
    name: "Web3.career London HR jobs",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://web3.career/web3-jobs-london%2Bhr",
    enabled: true,
    accessType: "public",
    notes: "London HR Web3 roles.",
  },
  {
    id: "cryptocurrency_jobs",
    name: "Cryptocurrency Jobs",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://cryptocurrencyjobs.co/",
    enabled: true,
    accessType: "public",
    notes: "Crypto jobs via public RSS; SWIFT ingests index.xml.",
  },
  {
    id: "cryptojobslist",
    name: "CryptoJobsList",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://cryptojobslist.com/",
    enabled: true,
    accessType: "public",
    notes: "Public crypto/Web3 job board; homepage HTML link discovery.",
  },
  {
    id: "remote3",
    name: "Remote3",
    sourceType: "job_board",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 2",
    url: "https://www.remote3.co/",
    enabled: true,
    accessType: "manual_review",
    notes:
      "Public Web3 remote jobs board; listings render client-side — no reliable static HTML URLs for ingestion v1.",
  },
  {
    id: "linkedin_job_alerts_outlook",
    name: "LinkedIn Job Alerts — Hotmail / Outlook",
    sourceType: "email_alert",
    topic: "jobs",
    category: "jobs",
    usedBy: ["job_opportunities", "skills_to_pick_up", "settings"],
    qualityTier: "Tier 1",
    url: "https://www.linkedin.com/jobs/",
    enabled: true,
    accessType: "email_alert",
    notes:
      "LinkedIn saved-search job alerts ingested from Hotmail / Outlook via Microsoft Power Automate. SWIFT does not scrape LinkedIn pages.",
  },
  {
    id: "cipd_employment_law_updates",
    name: "CIPD Employment Law updates",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["dashboard", "settings"],
    qualityTier: "Tier 1",
    url: "https://www.cipd.org/uk/knowledge/employment-law/legislation-updates/",
    enabled: true,
    accessType: "manual_review",
    notes: "UK employment law changes and people profession implications; manual review / future ingestion.",
  },
  {
    id: "cipd_employment_law_blog",
    name: "CIPD Employment Law blog",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["dashboard", "settings"],
    qualityTier: "Tier 1",
    url: "https://community.cipd.co.uk/cipd-blogs/b/employment_law",
    enabled: true,
    accessType: "manual_review",
    notes: "Employment law commentary; manual review / future ingestion.",
  },
  {
    id: "employment_law_worldview",
    name: "Employment Law Worldview",
    sourceType: "website",
    topic: "hr",
    category: "hrbp",
    usedBy: ["dashboard", "settings"],
    qualityTier: "Tier 1",
    url: "https://www.employmentlawworldview.com/",
    enabled: true,
    accessType: "manual_review",
    notes: "Global employment law insight from employment lawyers; manual review / future ingestion.",
  },
];

export function getEnabledSources() {
  return sourceRegistry.filter((s) => s.enabled);
}

export function getSourcesBySection(section: SwiftSection) {
  return sourceRegistry.filter((s) => s.usedBy.includes(section));
}

export function getSourcesByTopic(topic: SourceTopic) {
  return sourceRegistry.filter((s) => s.topic === topic);
}

export function getRssSources() {
  return sourceRegistry.filter((s) => s.sourceType === "rss");
}

export function getSourcesByType(type: SourceType) {
  return sourceRegistry.filter((s) => s.sourceType === type);
}

